// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rl_data_4_qtable.proto

#include "rl_data_4_qtable.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_rl_5fdata_5f4_5fqtable_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UeShare_rl_5fdata_5f4_5fqtable_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_rl_5fdata_5f4_5fqtable_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UeTTI_rl_5fdata_5f4_5fqtable_2eproto;
namespace rl_data_4_qtable {
class ObservationRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ObservationRequest> _instance;
} _ObservationRequest_default_instance_;
class ActionResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ActionResponse> _instance;
} _ActionResponse_default_instance_;
class UeShareDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UeShare> _instance;
} _UeShare_default_instance_;
class UeTTIDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UeTTI> _instance;
} _UeTTI_default_instance_;
}  // namespace rl_data_4_qtable
static void InitDefaultsscc_info_ActionResponse_rl_5fdata_5f4_5fqtable_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::rl_data_4_qtable::_ActionResponse_default_instance_;
    new (ptr) ::rl_data_4_qtable::ActionResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::rl_data_4_qtable::ActionResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ActionResponse_rl_5fdata_5f4_5fqtable_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ActionResponse_rl_5fdata_5f4_5fqtable_2eproto}, {
      &scc_info_UeShare_rl_5fdata_5f4_5fqtable_2eproto.base,}};

static void InitDefaultsscc_info_ObservationRequest_rl_5fdata_5f4_5fqtable_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::rl_data_4_qtable::_ObservationRequest_default_instance_;
    new (ptr) ::rl_data_4_qtable::ObservationRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::rl_data_4_qtable::ObservationRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ObservationRequest_rl_5fdata_5f4_5fqtable_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ObservationRequest_rl_5fdata_5f4_5fqtable_2eproto}, {
      &scc_info_UeTTI_rl_5fdata_5f4_5fqtable_2eproto.base,}};

static void InitDefaultsscc_info_UeShare_rl_5fdata_5f4_5fqtable_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::rl_data_4_qtable::_UeShare_default_instance_;
    new (ptr) ::rl_data_4_qtable::UeShare();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::rl_data_4_qtable::UeShare::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UeShare_rl_5fdata_5f4_5fqtable_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_UeShare_rl_5fdata_5f4_5fqtable_2eproto}, {}};

static void InitDefaultsscc_info_UeTTI_rl_5fdata_5f4_5fqtable_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::rl_data_4_qtable::_UeTTI_default_instance_;
    new (ptr) ::rl_data_4_qtable::UeTTI();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::rl_data_4_qtable::UeTTI::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UeTTI_rl_5fdata_5f4_5fqtable_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_UeTTI_rl_5fdata_5f4_5fqtable_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_rl_5fdata_5f4_5fqtable_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_rl_5fdata_5f4_5fqtable_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_rl_5fdata_5f4_5fqtable_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_rl_5fdata_5f4_5fqtable_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::ObservationRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::ObservationRequest, tti_phy_),
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::ObservationRequest, tti_counter_),
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::ObservationRequest, ues_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::ActionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::ActionResponse, ue_shares_),
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::ActionResponse, action_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::UeShare, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::UeShare, rnti_),
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::UeShare, share_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::UeTTI, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::UeTTI, rnti_),
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::UeTTI, txdrop_),
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::UeTTI, txbuffer_),
  PROTOBUF_FIELD_OFFSET(::rl_data_4_qtable::UeTTI, txpdu_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::rl_data_4_qtable::ObservationRequest)},
  { 8, -1, sizeof(::rl_data_4_qtable::ActionResponse)},
  { 15, -1, sizeof(::rl_data_4_qtable::UeShare)},
  { 22, -1, sizeof(::rl_data_4_qtable::UeTTI)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::rl_data_4_qtable::_ObservationRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::rl_data_4_qtable::_ActionResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::rl_data_4_qtable::_UeShare_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::rl_data_4_qtable::_UeTTI_default_instance_),
};

const char descriptor_table_protodef_rl_5fdata_5f4_5fqtable_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026rl_data_4_qtable.proto\022\020rl_data_4_qtab"
  "le\"`\n\022ObservationRequest\022\017\n\007tti_phy\030\001 \001("
  "\004\022\023\n\013tti_counter\030\002 \001(\004\022$\n\003ues\030\003 \003(\0132\027.rl"
  "_data_4_qtable.UeTTI\"Q\n\016ActionResponse\022,"
  "\n\tue_shares\030\001 \003(\0132\031.rl_data_4_qtable.UeS"
  "hare\022\021\n\taction_id\030\002 \001(\r\"&\n\007UeShare\022\014\n\004rn"
  "ti\030\001 \001(\r\022\r\n\005share\030\002 \001(\001\"F\n\005UeTTI\022\014\n\004rnti"
  "\030\001 \001(\r\022\016\n\006txdrop\030\002 \001(\004\022\020\n\010txbuffer\030\003 \001(\004"
  "\022\r\n\005txpdu\030\004 \001(\0042j\n\rRlData4QTable\022Y\n\017Push"
  "Observation\022$.rl_data_4_qtable.Observati"
  "onRequest\032 .rl_data_4_qtable.ActionRespo"
  "nseb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_rl_5fdata_5f4_5fqtable_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_rl_5fdata_5f4_5fqtable_2eproto_sccs[4] = {
  &scc_info_ActionResponse_rl_5fdata_5f4_5fqtable_2eproto.base,
  &scc_info_ObservationRequest_rl_5fdata_5f4_5fqtable_2eproto.base,
  &scc_info_UeShare_rl_5fdata_5f4_5fqtable_2eproto.base,
  &scc_info_UeTTI_rl_5fdata_5f4_5fqtable_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_rl_5fdata_5f4_5fqtable_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rl_5fdata_5f4_5fqtable_2eproto = {
  false, false, descriptor_table_protodef_rl_5fdata_5f4_5fqtable_2eproto, "rl_data_4_qtable.proto", 451,
  &descriptor_table_rl_5fdata_5f4_5fqtable_2eproto_once, descriptor_table_rl_5fdata_5f4_5fqtable_2eproto_sccs, descriptor_table_rl_5fdata_5f4_5fqtable_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_rl_5fdata_5f4_5fqtable_2eproto::offsets,
  file_level_metadata_rl_5fdata_5f4_5fqtable_2eproto, 4, file_level_enum_descriptors_rl_5fdata_5f4_5fqtable_2eproto, file_level_service_descriptors_rl_5fdata_5f4_5fqtable_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_rl_5fdata_5f4_5fqtable_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_rl_5fdata_5f4_5fqtable_2eproto)), true);
namespace rl_data_4_qtable {

// ===================================================================

void ObservationRequest::InitAsDefaultInstance() {
}
class ObservationRequest::_Internal {
 public:
};

ObservationRequest::ObservationRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  ues_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:rl_data_4_qtable.ObservationRequest)
}
ObservationRequest::ObservationRequest(const ObservationRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      ues_(from.ues_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&tti_phy_, &from.tti_phy_,
    static_cast<size_t>(reinterpret_cast<char*>(&tti_counter_) -
    reinterpret_cast<char*>(&tti_phy_)) + sizeof(tti_counter_));
  // @@protoc_insertion_point(copy_constructor:rl_data_4_qtable.ObservationRequest)
}

void ObservationRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ObservationRequest_rl_5fdata_5f4_5fqtable_2eproto.base);
  ::memset(&tti_phy_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tti_counter_) -
      reinterpret_cast<char*>(&tti_phy_)) + sizeof(tti_counter_));
}

ObservationRequest::~ObservationRequest() {
  // @@protoc_insertion_point(destructor:rl_data_4_qtable.ObservationRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ObservationRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ObservationRequest::ArenaDtor(void* object) {
  ObservationRequest* _this = reinterpret_cast< ObservationRequest* >(object);
  (void)_this;
}
void ObservationRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ObservationRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ObservationRequest& ObservationRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ObservationRequest_rl_5fdata_5f4_5fqtable_2eproto.base);
  return *internal_default_instance();
}


void ObservationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:rl_data_4_qtable.ObservationRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ues_.Clear();
  ::memset(&tti_phy_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tti_counter_) -
      reinterpret_cast<char*>(&tti_phy_)) + sizeof(tti_counter_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ObservationRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 tti_phy = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          tti_phy_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 tti_counter = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          tti_counter_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .rl_data_4_qtable.UeTTI ues = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ues(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ObservationRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl_data_4_qtable.ObservationRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 tti_phy = 1;
  if (this->tti_phy() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_tti_phy(), target);
  }

  // uint64 tti_counter = 2;
  if (this->tti_counter() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_tti_counter(), target);
  }

  // repeated .rl_data_4_qtable.UeTTI ues = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_ues_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_ues(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl_data_4_qtable.ObservationRequest)
  return target;
}

size_t ObservationRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl_data_4_qtable.ObservationRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .rl_data_4_qtable.UeTTI ues = 3;
  total_size += 1UL * this->_internal_ues_size();
  for (const auto& msg : this->ues_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint64 tti_phy = 1;
  if (this->tti_phy() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_tti_phy());
  }

  // uint64 tti_counter = 2;
  if (this->tti_counter() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_tti_counter());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ObservationRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:rl_data_4_qtable.ObservationRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ObservationRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ObservationRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:rl_data_4_qtable.ObservationRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:rl_data_4_qtable.ObservationRequest)
    MergeFrom(*source);
  }
}

void ObservationRequest::MergeFrom(const ObservationRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:rl_data_4_qtable.ObservationRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  ues_.MergeFrom(from.ues_);
  if (from.tti_phy() != 0) {
    _internal_set_tti_phy(from._internal_tti_phy());
  }
  if (from.tti_counter() != 0) {
    _internal_set_tti_counter(from._internal_tti_counter());
  }
}

void ObservationRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:rl_data_4_qtable.ObservationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObservationRequest::CopyFrom(const ObservationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl_data_4_qtable.ObservationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObservationRequest::IsInitialized() const {
  return true;
}

void ObservationRequest::InternalSwap(ObservationRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ues_.InternalSwap(&other->ues_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ObservationRequest, tti_counter_)
      + sizeof(ObservationRequest::tti_counter_)
      - PROTOBUF_FIELD_OFFSET(ObservationRequest, tti_phy_)>(
          reinterpret_cast<char*>(&tti_phy_),
          reinterpret_cast<char*>(&other->tti_phy_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ObservationRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ActionResponse::InitAsDefaultInstance() {
}
class ActionResponse::_Internal {
 public:
};

ActionResponse::ActionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  ue_shares_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:rl_data_4_qtable.ActionResponse)
}
ActionResponse::ActionResponse(const ActionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      ue_shares_(from.ue_shares_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  action_id_ = from.action_id_;
  // @@protoc_insertion_point(copy_constructor:rl_data_4_qtable.ActionResponse)
}

void ActionResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ActionResponse_rl_5fdata_5f4_5fqtable_2eproto.base);
  action_id_ = 0u;
}

ActionResponse::~ActionResponse() {
  // @@protoc_insertion_point(destructor:rl_data_4_qtable.ActionResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ActionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ActionResponse::ArenaDtor(void* object) {
  ActionResponse* _this = reinterpret_cast< ActionResponse* >(object);
  (void)_this;
}
void ActionResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ActionResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ActionResponse& ActionResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ActionResponse_rl_5fdata_5f4_5fqtable_2eproto.base);
  return *internal_default_instance();
}


void ActionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:rl_data_4_qtable.ActionResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ue_shares_.Clear();
  action_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActionResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .rl_data_4_qtable.UeShare ue_shares = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ue_shares(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      // uint32 action_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          action_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ActionResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl_data_4_qtable.ActionResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .rl_data_4_qtable.UeShare ue_shares = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_ue_shares_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_ue_shares(i), target, stream);
  }

  // uint32 action_id = 2;
  if (this->action_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_action_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl_data_4_qtable.ActionResponse)
  return target;
}

size_t ActionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl_data_4_qtable.ActionResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .rl_data_4_qtable.UeShare ue_shares = 1;
  total_size += 1UL * this->_internal_ue_shares_size();
  for (const auto& msg : this->ue_shares_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 action_id = 2;
  if (this->action_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_action_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ActionResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:rl_data_4_qtable.ActionResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ActionResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ActionResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:rl_data_4_qtable.ActionResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:rl_data_4_qtable.ActionResponse)
    MergeFrom(*source);
  }
}

void ActionResponse::MergeFrom(const ActionResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:rl_data_4_qtable.ActionResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  ue_shares_.MergeFrom(from.ue_shares_);
  if (from.action_id() != 0) {
    _internal_set_action_id(from._internal_action_id());
  }
}

void ActionResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:rl_data_4_qtable.ActionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ActionResponse::CopyFrom(const ActionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl_data_4_qtable.ActionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionResponse::IsInitialized() const {
  return true;
}

void ActionResponse::InternalSwap(ActionResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ue_shares_.InternalSwap(&other->ue_shares_);
  swap(action_id_, other->action_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActionResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void UeShare::InitAsDefaultInstance() {
}
class UeShare::_Internal {
 public:
};

UeShare::UeShare(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:rl_data_4_qtable.UeShare)
}
UeShare::UeShare(const UeShare& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&share_, &from.share_,
    static_cast<size_t>(reinterpret_cast<char*>(&rnti_) -
    reinterpret_cast<char*>(&share_)) + sizeof(rnti_));
  // @@protoc_insertion_point(copy_constructor:rl_data_4_qtable.UeShare)
}

void UeShare::SharedCtor() {
  ::memset(&share_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rnti_) -
      reinterpret_cast<char*>(&share_)) + sizeof(rnti_));
}

UeShare::~UeShare() {
  // @@protoc_insertion_point(destructor:rl_data_4_qtable.UeShare)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UeShare::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void UeShare::ArenaDtor(void* object) {
  UeShare* _this = reinterpret_cast< UeShare* >(object);
  (void)_this;
}
void UeShare::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UeShare::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UeShare& UeShare::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UeShare_rl_5fdata_5f4_5fqtable_2eproto.base);
  return *internal_default_instance();
}


void UeShare::Clear() {
// @@protoc_insertion_point(message_clear_start:rl_data_4_qtable.UeShare)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&share_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rnti_) -
      reinterpret_cast<char*>(&share_)) + sizeof(rnti_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UeShare::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 rnti = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          rnti_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double share = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          share_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UeShare::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl_data_4_qtable.UeShare)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 rnti = 1;
  if (this->rnti() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_rnti(), target);
  }

  // double share = 2;
  if (!(this->share() <= 0 && this->share() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_share(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl_data_4_qtable.UeShare)
  return target;
}

size_t UeShare::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl_data_4_qtable.UeShare)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double share = 2;
  if (!(this->share() <= 0 && this->share() >= 0)) {
    total_size += 1 + 8;
  }

  // uint32 rnti = 1;
  if (this->rnti() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_rnti());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UeShare::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:rl_data_4_qtable.UeShare)
  GOOGLE_DCHECK_NE(&from, this);
  const UeShare* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UeShare>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:rl_data_4_qtable.UeShare)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:rl_data_4_qtable.UeShare)
    MergeFrom(*source);
  }
}

void UeShare::MergeFrom(const UeShare& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:rl_data_4_qtable.UeShare)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.share() <= 0 && from.share() >= 0)) {
    _internal_set_share(from._internal_share());
  }
  if (from.rnti() != 0) {
    _internal_set_rnti(from._internal_rnti());
  }
}

void UeShare::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:rl_data_4_qtable.UeShare)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UeShare::CopyFrom(const UeShare& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl_data_4_qtable.UeShare)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UeShare::IsInitialized() const {
  return true;
}

void UeShare::InternalSwap(UeShare* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UeShare, rnti_)
      + sizeof(UeShare::rnti_)
      - PROTOBUF_FIELD_OFFSET(UeShare, share_)>(
          reinterpret_cast<char*>(&share_),
          reinterpret_cast<char*>(&other->share_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UeShare::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void UeTTI::InitAsDefaultInstance() {
}
class UeTTI::_Internal {
 public:
};

UeTTI::UeTTI(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:rl_data_4_qtable.UeTTI)
}
UeTTI::UeTTI(const UeTTI& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&txdrop_, &from.txdrop_,
    static_cast<size_t>(reinterpret_cast<char*>(&rnti_) -
    reinterpret_cast<char*>(&txdrop_)) + sizeof(rnti_));
  // @@protoc_insertion_point(copy_constructor:rl_data_4_qtable.UeTTI)
}

void UeTTI::SharedCtor() {
  ::memset(&txdrop_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rnti_) -
      reinterpret_cast<char*>(&txdrop_)) + sizeof(rnti_));
}

UeTTI::~UeTTI() {
  // @@protoc_insertion_point(destructor:rl_data_4_qtable.UeTTI)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UeTTI::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void UeTTI::ArenaDtor(void* object) {
  UeTTI* _this = reinterpret_cast< UeTTI* >(object);
  (void)_this;
}
void UeTTI::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UeTTI::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UeTTI& UeTTI::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UeTTI_rl_5fdata_5f4_5fqtable_2eproto.base);
  return *internal_default_instance();
}


void UeTTI::Clear() {
// @@protoc_insertion_point(message_clear_start:rl_data_4_qtable.UeTTI)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&txdrop_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rnti_) -
      reinterpret_cast<char*>(&txdrop_)) + sizeof(rnti_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UeTTI::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 rnti = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          rnti_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 txdrop = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          txdrop_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 txbuffer = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          txbuffer_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 txpdu = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          txpdu_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UeTTI::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rl_data_4_qtable.UeTTI)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 rnti = 1;
  if (this->rnti() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_rnti(), target);
  }

  // uint64 txdrop = 2;
  if (this->txdrop() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_txdrop(), target);
  }

  // uint64 txbuffer = 3;
  if (this->txbuffer() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->_internal_txbuffer(), target);
  }

  // uint64 txpdu = 4;
  if (this->txpdu() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(4, this->_internal_txpdu(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rl_data_4_qtable.UeTTI)
  return target;
}

size_t UeTTI::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rl_data_4_qtable.UeTTI)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 txdrop = 2;
  if (this->txdrop() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_txdrop());
  }

  // uint64 txbuffer = 3;
  if (this->txbuffer() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_txbuffer());
  }

  // uint64 txpdu = 4;
  if (this->txpdu() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_txpdu());
  }

  // uint32 rnti = 1;
  if (this->rnti() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_rnti());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UeTTI::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:rl_data_4_qtable.UeTTI)
  GOOGLE_DCHECK_NE(&from, this);
  const UeTTI* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UeTTI>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:rl_data_4_qtable.UeTTI)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:rl_data_4_qtable.UeTTI)
    MergeFrom(*source);
  }
}

void UeTTI::MergeFrom(const UeTTI& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:rl_data_4_qtable.UeTTI)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.txdrop() != 0) {
    _internal_set_txdrop(from._internal_txdrop());
  }
  if (from.txbuffer() != 0) {
    _internal_set_txbuffer(from._internal_txbuffer());
  }
  if (from.txpdu() != 0) {
    _internal_set_txpdu(from._internal_txpdu());
  }
  if (from.rnti() != 0) {
    _internal_set_rnti(from._internal_rnti());
  }
}

void UeTTI::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:rl_data_4_qtable.UeTTI)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UeTTI::CopyFrom(const UeTTI& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rl_data_4_qtable.UeTTI)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UeTTI::IsInitialized() const {
  return true;
}

void UeTTI::InternalSwap(UeTTI* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UeTTI, rnti_)
      + sizeof(UeTTI::rnti_)
      - PROTOBUF_FIELD_OFFSET(UeTTI, txdrop_)>(
          reinterpret_cast<char*>(&txdrop_),
          reinterpret_cast<char*>(&other->txdrop_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UeTTI::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace rl_data_4_qtable
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rl_data_4_qtable::ObservationRequest* Arena::CreateMaybeMessage< ::rl_data_4_qtable::ObservationRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl_data_4_qtable::ObservationRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::rl_data_4_qtable::ActionResponse* Arena::CreateMaybeMessage< ::rl_data_4_qtable::ActionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl_data_4_qtable::ActionResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::rl_data_4_qtable::UeShare* Arena::CreateMaybeMessage< ::rl_data_4_qtable::UeShare >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl_data_4_qtable::UeShare >(arena);
}
template<> PROTOBUF_NOINLINE ::rl_data_4_qtable::UeTTI* Arena::CreateMaybeMessage< ::rl_data_4_qtable::UeTTI >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rl_data_4_qtable::UeTTI >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
