// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rl_data_4_qtable.proto

#include "rl_data_4_qtable.pb.h"
#include "rl_data_4_qtable.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace rl_data_4_qtable {

static const char* RlData4QTable_method_names[] = {
  "/rl_data_4_qtable.RlData4QTable/PushObservation",
};

std::unique_ptr< RlData4QTable::Stub> RlData4QTable::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RlData4QTable::Stub> stub(new RlData4QTable::Stub(channel));
  return stub;
}

RlData4QTable::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PushObservation_(RlData4QTable_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RlData4QTable::Stub::PushObservation(::grpc::ClientContext* context, const ::rl_data_4_qtable::ObservationRequest& request, ::rl_data_4_qtable::ActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PushObservation_, context, request, response);
}

void RlData4QTable::Stub::experimental_async::PushObservation(::grpc::ClientContext* context, const ::rl_data_4_qtable::ObservationRequest* request, ::rl_data_4_qtable::ActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PushObservation_, context, request, response, std::move(f));
}

void RlData4QTable::Stub::experimental_async::PushObservation(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rl_data_4_qtable::ActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PushObservation_, context, request, response, std::move(f));
}

void RlData4QTable::Stub::experimental_async::PushObservation(::grpc::ClientContext* context, const ::rl_data_4_qtable::ObservationRequest* request, ::rl_data_4_qtable::ActionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PushObservation_, context, request, response, reactor);
}

void RlData4QTable::Stub::experimental_async::PushObservation(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rl_data_4_qtable::ActionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PushObservation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rl_data_4_qtable::ActionResponse>* RlData4QTable::Stub::AsyncPushObservationRaw(::grpc::ClientContext* context, const ::rl_data_4_qtable::ObservationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::rl_data_4_qtable::ActionResponse>::Create(channel_.get(), cq, rpcmethod_PushObservation_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::rl_data_4_qtable::ActionResponse>* RlData4QTable::Stub::PrepareAsyncPushObservationRaw(::grpc::ClientContext* context, const ::rl_data_4_qtable::ObservationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::rl_data_4_qtable::ActionResponse>::Create(channel_.get(), cq, rpcmethod_PushObservation_, context, request, false);
}

RlData4QTable::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RlData4QTable_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RlData4QTable::Service, ::rl_data_4_qtable::ObservationRequest, ::rl_data_4_qtable::ActionResponse>(
          [](RlData4QTable::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::rl_data_4_qtable::ObservationRequest* req,
             ::rl_data_4_qtable::ActionResponse* resp) {
               return service->PushObservation(ctx, req, resp);
             }, this)));
}

RlData4QTable::Service::~Service() {
}

::grpc::Status RlData4QTable::Service::PushObservation(::grpc::ServerContext* context, const ::rl_data_4_qtable::ObservationRequest* request, ::rl_data_4_qtable::ActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rl_data_4_qtable

