# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rl_data_4_qtable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rl_data_4_qtable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16rl_data_4_qtable.proto\x12\x10rl_data_4_qtable\"`\n\x12ObservationRequest\x12\x0f\n\x07tti_phy\x18\x01 \x01(\x04\x12\x13\n\x0btti_counter\x18\x02 \x01(\x04\x12$\n\x03ues\x18\x03 \x03(\x0b\x32\x17.rl_data_4_qtable.UeTTI\"Q\n\x0e\x41\x63tionResponse\x12,\n\tue_shares\x18\x01 \x03(\x0b\x32\x19.rl_data_4_qtable.UeShare\x12\x11\n\taction_id\x18\x02 \x01(\r\"&\n\x07UeShare\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\r\n\x05share\x18\x02 \x01(\x01\"F\n\x05UeTTI\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x0e\n\x06txdrop\x18\x02 \x01(\x04\x12\x10\n\x08txbuffer\x18\x03 \x01(\x04\x12\r\n\x05txpdu\x18\x04 \x01(\x04\x32j\n\rRlData4QTable\x12Y\n\x0fPushObservation\x12$.rl_data_4_qtable.ObservationRequest\x1a .rl_data_4_qtable.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rl_data_4_qtable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATIONREQUEST']._serialized_start=44
  _globals['_OBSERVATIONREQUEST']._serialized_end=140
  _globals['_ACTIONRESPONSE']._serialized_start=142
  _globals['_ACTIONRESPONSE']._serialized_end=223
  _globals['_UESHARE']._serialized_start=225
  _globals['_UESHARE']._serialized_end=263
  _globals['_UETTI']._serialized_start=265
  _globals['_UETTI']._serialized_end=335
  _globals['_RLDATA4QTABLE']._serialized_start=337
  _globals['_RLDATA4QTABLE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
