// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rl_data_4_qtable.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rl_5fdata_5f4_5fqtable_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rl_5fdata_5f4_5fqtable_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rl_5fdata_5f4_5fqtable_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rl_5fdata_5f4_5fqtable_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rl_5fdata_5f4_5fqtable_2eproto;
namespace rl_data_4_qtable {
class ActionResponse;
class ActionResponseDefaultTypeInternal;
extern ActionResponseDefaultTypeInternal _ActionResponse_default_instance_;
class ObservationRequest;
class ObservationRequestDefaultTypeInternal;
extern ObservationRequestDefaultTypeInternal _ObservationRequest_default_instance_;
class UeShare;
class UeShareDefaultTypeInternal;
extern UeShareDefaultTypeInternal _UeShare_default_instance_;
class UeTTI;
class UeTTIDefaultTypeInternal;
extern UeTTIDefaultTypeInternal _UeTTI_default_instance_;
}  // namespace rl_data_4_qtable
PROTOBUF_NAMESPACE_OPEN
template<> ::rl_data_4_qtable::ActionResponse* Arena::CreateMaybeMessage<::rl_data_4_qtable::ActionResponse>(Arena*);
template<> ::rl_data_4_qtable::ObservationRequest* Arena::CreateMaybeMessage<::rl_data_4_qtable::ObservationRequest>(Arena*);
template<> ::rl_data_4_qtable::UeShare* Arena::CreateMaybeMessage<::rl_data_4_qtable::UeShare>(Arena*);
template<> ::rl_data_4_qtable::UeTTI* Arena::CreateMaybeMessage<::rl_data_4_qtable::UeTTI>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rl_data_4_qtable {

// ===================================================================

class ObservationRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl_data_4_qtable.ObservationRequest) */ {
 public:
  inline ObservationRequest() : ObservationRequest(nullptr) {};
  virtual ~ObservationRequest();

  ObservationRequest(const ObservationRequest& from);
  ObservationRequest(ObservationRequest&& from) noexcept
    : ObservationRequest() {
    *this = ::std::move(from);
  }

  inline ObservationRequest& operator=(const ObservationRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObservationRequest& operator=(ObservationRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ObservationRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ObservationRequest* internal_default_instance() {
    return reinterpret_cast<const ObservationRequest*>(
               &_ObservationRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ObservationRequest& a, ObservationRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ObservationRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObservationRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ObservationRequest* New() const final {
    return CreateMaybeMessage<ObservationRequest>(nullptr);
  }

  ObservationRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ObservationRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ObservationRequest& from);
  void MergeFrom(const ObservationRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObservationRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl_data_4_qtable.ObservationRequest";
  }
  protected:
  explicit ObservationRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rl_5fdata_5f4_5fqtable_2eproto);
    return ::descriptor_table_rl_5fdata_5f4_5fqtable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUesFieldNumber = 3,
    kTtiPhyFieldNumber = 1,
    kTtiCounterFieldNumber = 2,
  };
  // repeated .rl_data_4_qtable.UeTTI ues = 3;
  int ues_size() const;
  private:
  int _internal_ues_size() const;
  public:
  void clear_ues();
  ::rl_data_4_qtable::UeTTI* mutable_ues(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeTTI >*
      mutable_ues();
  private:
  const ::rl_data_4_qtable::UeTTI& _internal_ues(int index) const;
  ::rl_data_4_qtable::UeTTI* _internal_add_ues();
  public:
  const ::rl_data_4_qtable::UeTTI& ues(int index) const;
  ::rl_data_4_qtable::UeTTI* add_ues();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeTTI >&
      ues() const;

  // uint64 tti_phy = 1;
  void clear_tti_phy();
  ::PROTOBUF_NAMESPACE_ID::uint64 tti_phy() const;
  void set_tti_phy(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_tti_phy() const;
  void _internal_set_tti_phy(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 tti_counter = 2;
  void clear_tti_counter();
  ::PROTOBUF_NAMESPACE_ID::uint64 tti_counter() const;
  void set_tti_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_tti_counter() const;
  void _internal_set_tti_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:rl_data_4_qtable.ObservationRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeTTI > ues_;
  ::PROTOBUF_NAMESPACE_ID::uint64 tti_phy_;
  ::PROTOBUF_NAMESPACE_ID::uint64 tti_counter_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rl_5fdata_5f4_5fqtable_2eproto;
};
// -------------------------------------------------------------------

class ActionResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl_data_4_qtable.ActionResponse) */ {
 public:
  inline ActionResponse() : ActionResponse(nullptr) {};
  virtual ~ActionResponse();

  ActionResponse(const ActionResponse& from);
  ActionResponse(ActionResponse&& from) noexcept
    : ActionResponse() {
    *this = ::std::move(from);
  }

  inline ActionResponse& operator=(const ActionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActionResponse& operator=(ActionResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ActionResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ActionResponse* internal_default_instance() {
    return reinterpret_cast<const ActionResponse*>(
               &_ActionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ActionResponse& a, ActionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ActionResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ActionResponse* New() const final {
    return CreateMaybeMessage<ActionResponse>(nullptr);
  }

  ActionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ActionResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ActionResponse& from);
  void MergeFrom(const ActionResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActionResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl_data_4_qtable.ActionResponse";
  }
  protected:
  explicit ActionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rl_5fdata_5f4_5fqtable_2eproto);
    return ::descriptor_table_rl_5fdata_5f4_5fqtable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUeSharesFieldNumber = 1,
    kActionIdFieldNumber = 2,
  };
  // repeated .rl_data_4_qtable.UeShare ue_shares = 1;
  int ue_shares_size() const;
  private:
  int _internal_ue_shares_size() const;
  public:
  void clear_ue_shares();
  ::rl_data_4_qtable::UeShare* mutable_ue_shares(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeShare >*
      mutable_ue_shares();
  private:
  const ::rl_data_4_qtable::UeShare& _internal_ue_shares(int index) const;
  ::rl_data_4_qtable::UeShare* _internal_add_ue_shares();
  public:
  const ::rl_data_4_qtable::UeShare& ue_shares(int index) const;
  ::rl_data_4_qtable::UeShare* add_ue_shares();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeShare >&
      ue_shares() const;

  // uint32 action_id = 2;
  void clear_action_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 action_id() const;
  void set_action_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_action_id() const;
  void _internal_set_action_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:rl_data_4_qtable.ActionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeShare > ue_shares_;
  ::PROTOBUF_NAMESPACE_ID::uint32 action_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rl_5fdata_5f4_5fqtable_2eproto;
};
// -------------------------------------------------------------------

class UeShare PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl_data_4_qtable.UeShare) */ {
 public:
  inline UeShare() : UeShare(nullptr) {};
  virtual ~UeShare();

  UeShare(const UeShare& from);
  UeShare(UeShare&& from) noexcept
    : UeShare() {
    *this = ::std::move(from);
  }

  inline UeShare& operator=(const UeShare& from) {
    CopyFrom(from);
    return *this;
  }
  inline UeShare& operator=(UeShare&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UeShare& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UeShare* internal_default_instance() {
    return reinterpret_cast<const UeShare*>(
               &_UeShare_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UeShare& a, UeShare& b) {
    a.Swap(&b);
  }
  inline void Swap(UeShare* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UeShare* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UeShare* New() const final {
    return CreateMaybeMessage<UeShare>(nullptr);
  }

  UeShare* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UeShare>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UeShare& from);
  void MergeFrom(const UeShare& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UeShare* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl_data_4_qtable.UeShare";
  }
  protected:
  explicit UeShare(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rl_5fdata_5f4_5fqtable_2eproto);
    return ::descriptor_table_rl_5fdata_5f4_5fqtable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShareFieldNumber = 2,
    kRntiFieldNumber = 1,
  };
  // double share = 2;
  void clear_share();
  double share() const;
  void set_share(double value);
  private:
  double _internal_share() const;
  void _internal_set_share(double value);
  public:

  // uint32 rnti = 1;
  void clear_rnti();
  ::PROTOBUF_NAMESPACE_ID::uint32 rnti() const;
  void set_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rnti() const;
  void _internal_set_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:rl_data_4_qtable.UeShare)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double share_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rnti_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rl_5fdata_5f4_5fqtable_2eproto;
};
// -------------------------------------------------------------------

class UeTTI PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rl_data_4_qtable.UeTTI) */ {
 public:
  inline UeTTI() : UeTTI(nullptr) {};
  virtual ~UeTTI();

  UeTTI(const UeTTI& from);
  UeTTI(UeTTI&& from) noexcept
    : UeTTI() {
    *this = ::std::move(from);
  }

  inline UeTTI& operator=(const UeTTI& from) {
    CopyFrom(from);
    return *this;
  }
  inline UeTTI& operator=(UeTTI&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UeTTI& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UeTTI* internal_default_instance() {
    return reinterpret_cast<const UeTTI*>(
               &_UeTTI_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(UeTTI& a, UeTTI& b) {
    a.Swap(&b);
  }
  inline void Swap(UeTTI* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UeTTI* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UeTTI* New() const final {
    return CreateMaybeMessage<UeTTI>(nullptr);
  }

  UeTTI* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UeTTI>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UeTTI& from);
  void MergeFrom(const UeTTI& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UeTTI* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rl_data_4_qtable.UeTTI";
  }
  protected:
  explicit UeTTI(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rl_5fdata_5f4_5fqtable_2eproto);
    return ::descriptor_table_rl_5fdata_5f4_5fqtable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTxdropFieldNumber = 2,
    kTxbufferFieldNumber = 3,
    kTxpduFieldNumber = 4,
    kRntiFieldNumber = 1,
  };
  // uint64 txdrop = 2;
  void clear_txdrop();
  ::PROTOBUF_NAMESPACE_ID::uint64 txdrop() const;
  void set_txdrop(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_txdrop() const;
  void _internal_set_txdrop(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 txbuffer = 3;
  void clear_txbuffer();
  ::PROTOBUF_NAMESPACE_ID::uint64 txbuffer() const;
  void set_txbuffer(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_txbuffer() const;
  void _internal_set_txbuffer(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 txpdu = 4;
  void clear_txpdu();
  ::PROTOBUF_NAMESPACE_ID::uint64 txpdu() const;
  void set_txpdu(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_txpdu() const;
  void _internal_set_txpdu(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 rnti = 1;
  void clear_rnti();
  ::PROTOBUF_NAMESPACE_ID::uint32 rnti() const;
  void set_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rnti() const;
  void _internal_set_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:rl_data_4_qtable.UeTTI)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 txdrop_;
  ::PROTOBUF_NAMESPACE_ID::uint64 txbuffer_;
  ::PROTOBUF_NAMESPACE_ID::uint64 txpdu_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rnti_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rl_5fdata_5f4_5fqtable_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ObservationRequest

// uint64 tti_phy = 1;
inline void ObservationRequest::clear_tti_phy() {
  tti_phy_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ObservationRequest::_internal_tti_phy() const {
  return tti_phy_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ObservationRequest::tti_phy() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.ObservationRequest.tti_phy)
  return _internal_tti_phy();
}
inline void ObservationRequest::_internal_set_tti_phy(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  tti_phy_ = value;
}
inline void ObservationRequest::set_tti_phy(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_tti_phy(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.ObservationRequest.tti_phy)
}

// uint64 tti_counter = 2;
inline void ObservationRequest::clear_tti_counter() {
  tti_counter_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ObservationRequest::_internal_tti_counter() const {
  return tti_counter_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ObservationRequest::tti_counter() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.ObservationRequest.tti_counter)
  return _internal_tti_counter();
}
inline void ObservationRequest::_internal_set_tti_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  tti_counter_ = value;
}
inline void ObservationRequest::set_tti_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_tti_counter(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.ObservationRequest.tti_counter)
}

// repeated .rl_data_4_qtable.UeTTI ues = 3;
inline int ObservationRequest::_internal_ues_size() const {
  return ues_.size();
}
inline int ObservationRequest::ues_size() const {
  return _internal_ues_size();
}
inline void ObservationRequest::clear_ues() {
  ues_.Clear();
}
inline ::rl_data_4_qtable::UeTTI* ObservationRequest::mutable_ues(int index) {
  // @@protoc_insertion_point(field_mutable:rl_data_4_qtable.ObservationRequest.ues)
  return ues_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeTTI >*
ObservationRequest::mutable_ues() {
  // @@protoc_insertion_point(field_mutable_list:rl_data_4_qtable.ObservationRequest.ues)
  return &ues_;
}
inline const ::rl_data_4_qtable::UeTTI& ObservationRequest::_internal_ues(int index) const {
  return ues_.Get(index);
}
inline const ::rl_data_4_qtable::UeTTI& ObservationRequest::ues(int index) const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.ObservationRequest.ues)
  return _internal_ues(index);
}
inline ::rl_data_4_qtable::UeTTI* ObservationRequest::_internal_add_ues() {
  return ues_.Add();
}
inline ::rl_data_4_qtable::UeTTI* ObservationRequest::add_ues() {
  // @@protoc_insertion_point(field_add:rl_data_4_qtable.ObservationRequest.ues)
  return _internal_add_ues();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeTTI >&
ObservationRequest::ues() const {
  // @@protoc_insertion_point(field_list:rl_data_4_qtable.ObservationRequest.ues)
  return ues_;
}

// -------------------------------------------------------------------

// ActionResponse

// repeated .rl_data_4_qtable.UeShare ue_shares = 1;
inline int ActionResponse::_internal_ue_shares_size() const {
  return ue_shares_.size();
}
inline int ActionResponse::ue_shares_size() const {
  return _internal_ue_shares_size();
}
inline void ActionResponse::clear_ue_shares() {
  ue_shares_.Clear();
}
inline ::rl_data_4_qtable::UeShare* ActionResponse::mutable_ue_shares(int index) {
  // @@protoc_insertion_point(field_mutable:rl_data_4_qtable.ActionResponse.ue_shares)
  return ue_shares_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeShare >*
ActionResponse::mutable_ue_shares() {
  // @@protoc_insertion_point(field_mutable_list:rl_data_4_qtable.ActionResponse.ue_shares)
  return &ue_shares_;
}
inline const ::rl_data_4_qtable::UeShare& ActionResponse::_internal_ue_shares(int index) const {
  return ue_shares_.Get(index);
}
inline const ::rl_data_4_qtable::UeShare& ActionResponse::ue_shares(int index) const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.ActionResponse.ue_shares)
  return _internal_ue_shares(index);
}
inline ::rl_data_4_qtable::UeShare* ActionResponse::_internal_add_ue_shares() {
  return ue_shares_.Add();
}
inline ::rl_data_4_qtable::UeShare* ActionResponse::add_ue_shares() {
  // @@protoc_insertion_point(field_add:rl_data_4_qtable.ActionResponse.ue_shares)
  return _internal_add_ue_shares();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rl_data_4_qtable::UeShare >&
ActionResponse::ue_shares() const {
  // @@protoc_insertion_point(field_list:rl_data_4_qtable.ActionResponse.ue_shares)
  return ue_shares_;
}

// uint32 action_id = 2;
inline void ActionResponse::clear_action_id() {
  action_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ActionResponse::_internal_action_id() const {
  return action_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ActionResponse::action_id() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.ActionResponse.action_id)
  return _internal_action_id();
}
inline void ActionResponse::_internal_set_action_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  action_id_ = value;
}
inline void ActionResponse::set_action_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_action_id(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.ActionResponse.action_id)
}

// -------------------------------------------------------------------

// UeShare

// uint32 rnti = 1;
inline void UeShare::clear_rnti() {
  rnti_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UeShare::_internal_rnti() const {
  return rnti_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UeShare::rnti() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.UeShare.rnti)
  return _internal_rnti();
}
inline void UeShare::_internal_set_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rnti_ = value;
}
inline void UeShare::set_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rnti(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.UeShare.rnti)
}

// double share = 2;
inline void UeShare::clear_share() {
  share_ = 0;
}
inline double UeShare::_internal_share() const {
  return share_;
}
inline double UeShare::share() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.UeShare.share)
  return _internal_share();
}
inline void UeShare::_internal_set_share(double value) {
  
  share_ = value;
}
inline void UeShare::set_share(double value) {
  _internal_set_share(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.UeShare.share)
}

// -------------------------------------------------------------------

// UeTTI

// uint32 rnti = 1;
inline void UeTTI::clear_rnti() {
  rnti_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UeTTI::_internal_rnti() const {
  return rnti_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UeTTI::rnti() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.UeTTI.rnti)
  return _internal_rnti();
}
inline void UeTTI::_internal_set_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rnti_ = value;
}
inline void UeTTI::set_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rnti(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.UeTTI.rnti)
}

// uint64 txdrop = 2;
inline void UeTTI::clear_txdrop() {
  txdrop_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UeTTI::_internal_txdrop() const {
  return txdrop_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UeTTI::txdrop() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.UeTTI.txdrop)
  return _internal_txdrop();
}
inline void UeTTI::_internal_set_txdrop(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  txdrop_ = value;
}
inline void UeTTI::set_txdrop(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_txdrop(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.UeTTI.txdrop)
}

// uint64 txbuffer = 3;
inline void UeTTI::clear_txbuffer() {
  txbuffer_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UeTTI::_internal_txbuffer() const {
  return txbuffer_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UeTTI::txbuffer() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.UeTTI.txbuffer)
  return _internal_txbuffer();
}
inline void UeTTI::_internal_set_txbuffer(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  txbuffer_ = value;
}
inline void UeTTI::set_txbuffer(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_txbuffer(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.UeTTI.txbuffer)
}

// uint64 txpdu = 4;
inline void UeTTI::clear_txpdu() {
  txpdu_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UeTTI::_internal_txpdu() const {
  return txpdu_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UeTTI::txpdu() const {
  // @@protoc_insertion_point(field_get:rl_data_4_qtable.UeTTI.txpdu)
  return _internal_txpdu();
}
inline void UeTTI::_internal_set_txpdu(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  txpdu_ = value;
}
inline void UeTTI::set_txpdu(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_txpdu(value);
  // @@protoc_insertion_point(field_set:rl_data_4_qtable.UeTTI.txpdu)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rl_data_4_qtable

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rl_5fdata_5f4_5fqtable_2eproto
